public class AccountConstants {
    public final String OBJECT_NAME {
        get {
            return 'Account';
        }
        private set;
    }
    public final String ID_FIELD {
        get {
            return 'Id';
        }
        private set;
    }
    public final String NAME_FIELD {
        get {
            return 'Name';
        }
        private set;
    }
    public final String TYPE_FIELD {
        get {
            return 'Type';
        }
        private set;
    }
    public final String INDUSTRY_FIELD {
        get {
            return 'Industry';
        }
        private set;
    }
    public final String PHONE_FIELD {
        get {
            return 'Phone';
        }
        private set;
    }
    public final String TYPE_PROSPECT {
        get {
            return 'Prospect';
        }
        private set;
    }
    public final String TYPE_OTHER {
        get {
            return 'Other';
        }
        private set;
    }
    public final String INDUSTRY_BANKING {
        get {
            return 'Banking';
        }
        private set;
    }
    public final String INDUSTRY_CHEMICALS {
        get {
            return 'Chemicals';
        }
        private set;
    }
}