public class ContractConstants {
    public final String OBJECT_NAME {
        get {
            return 'Contract';
        }
        private set;
    }

    public final String  STATUS_ACTIVATED {
        get {
            return 'Activated';
        }
        private set;
    }

    public final String  STATUS_DRAFT {
        get {
            return 'Draft';
        }
        private set;
    }
}