public class OpportunityConstants {
    public final String OBJECT_NAME {
        get {
            return 'Opportunity';
        }
        private set;
    }
    public final String TYPE_NEW_BUSINESS {
        get {
            return 'New Business';
        }
        private set;
    }
    public final String STAGE_NAME_QUALIFICATION {
        get {
            return 'Qualification';
        }
        private set;
    }
}