public class PricebookEntryConstants {
    public final String OBJECT_NAME {
        get {
            return 'PricebookEntry';
        }
        private set;
    }

    public final String PRODUCT_ID_FIELD {
        get {
            return 'Product2Id';
        }
        private set;
    }

    public final String PRODUCT_NAME_FIELD {
        get {
            return 'Product2.Name';
        }
        private set;
    }

    public final String PRODUCT_CODE_FIELD {
        get {
            return 'Product2.ProductCode';
        }
        private set;
    }

    public final String PRODUCT_FAMILY_FIELD {
        get {
            return 'Product2.Family';
        }
        private set;
    }

    public final String PRICEBOOK_ID_FIELD {
        get {
            return 'Pricebook2Id';
        }
        private set;
    }
}