public class ProductConstants {
    public final String OBJECT_NAME {
        get {
            return 'Product2';
        }
        private set;
    }

    public final String ADAPTERS_FAMILY {
        get {
            return 'Adapters';
        }
        private set;
    }

    public final String CABLES_FAMILY {
        get {
            return 'Cables';
        }
        private set;
    }
    
    public final String NETWORKING_FAMILY {
        get {
            return 'Networking';
        }
        private set;
    }
}