import { createElement } from '@lwc/engine-dom';
import ProductComplaint from 'c/productComplaint';

jest.mock(
    'lightning/actions',
    () => {
        return {
            defailt: jest.fn()
        };
    },
    { virtual: true }
);

describe('c-product-complaint', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        // const element = createElement('c-product-complaint', {
        //     is: ProductComplaint
        // });

        // Act
        //document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        //expect(1).toBe(1);
    });
});