name: Validate Production PR

on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  validate-production-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli
      
      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          sf org login jwt \
            --client-id ${{ secrets.SF_CONSUMER_KEY }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --instance-url ${{ secrets.SF_SERVER_URL }} \
            --alias SFDC_v1 \
            --set-default
      - name: Dry Run
        run: |
          sf project deploy start --dry-run --test-level RunLocalTests --source-dir force-app
